# Generated by Django 4.2.7 on 2023-11-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_checket_alter_answer_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='checket',
            new_name='selected',
        ),
    ]
